name: Docs

on:
  #push:
  #  branches:
  #  - master
  #  - 3.8
  #  - 3.7
  #  paths:
  #  - 'Doc/**'
  pull_request:
    branches:
    - master
    - 3.8
    - 3.7
    paths:
    - 'Doc/**'
    - 'Misc/**'

jobs:
  build_doc:
    name: 'Docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: 'Install build dependencies'
      run: python -m pip install sphinx==2.2.0 blurb python-docs-theme
    - name: 'Build documentation'
      run: |
        cd Doc
        make check suspicious html PYTHON=python
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: doc-html
        path: Doc/build/html
